//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XIVEVENT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XIVEVENT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feel like you want to make a donation?  It would be gratefully received.  Click the button to donate via GitHub sponsors..
        /// </summary>
        public static string AboutTabItem_DonationText {
            get {
                return ResourceManager.GetString("AboutTabItem_DonationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say hello, make a feature request, or raise a bug through one of these channels:.
        /// </summary>
        public static string AboutTabItem_GetInTouchExtendedText {
            get {
                return ResourceManager.GetString("AboutTabItem_GetInTouchExtendedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get In Touch.
        /// </summary>
        public static string AboutTabItem_GetInTouchText {
            get {
                return ResourceManager.GetString("AboutTabItem_GetInTouchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project is completely open source. If you like it and want to say thanks you could hit the GitHub Star button, tweet or post about it, or tell your mum about it!.
        /// </summary>
        public static string AboutTabItem_OpenSourceExtendedText {
            get {
                return ResourceManager.GetString("AboutTabItem_OpenSourceExtendedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Source.
        /// </summary>
        public static string AboutTabItem_OpenSourceText {
            get {
                return ResourceManager.GetString("AboutTabItem_OpenSourceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XIVEVENT.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string ChatCodes_SaveChangesText {
            get {
                return ResourceManager.GetString("ChatCodes_SaveChangesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string EventItem_CategoryText {
            get {
                return ResourceManager.GetString("EventItem_CategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Enabled.
        /// </summary>
        public static string EventItem_EventEnabledText {
            get {
                return ResourceManager.GetString("EventItem_EventEnabledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable Arguments.
        /// </summary>
        public static string EventItem_ExecutableArgumentsText {
            get {
                return ResourceManager.GetString("EventItem_ExecutableArgumentsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable Path.
        /// </summary>
        public static string EventItem_ExecutablePathText {
            get {
                return ResourceManager.GetString("EventItem_ExecutablePathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegEx.
        /// </summary>
        public static string EventItem_RegularExpressionText {
            get {
                return ResourceManager.GetString("EventItem_RegularExpressionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        public static string EventItem_SoundText {
            get {
                return ResourceManager.GetString("EventItem_SoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech Rate.
        /// </summary>
        public static string EventItem_SpeechRateText {
            get {
                return ResourceManager.GetString("EventItem_SpeechRateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTS Message.
        /// </summary>
        public static string EventItem_TTSMessageText {
            get {
                return ResourceManager.GetString("EventItem_TTSMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string EventItem_VolumeText {
            get {
                return ResourceManager.GetString("EventItem_VolumeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Event.
        /// </summary>
        public static string HomeTabItem_CreateEventText {
            get {
                return ResourceManager.GetString("HomeTabItem_CreateEventText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Event.
        /// </summary>
        public static string HomeTabItem_DeleteEventItemText {
            get {
                return ResourceManager.GetString("HomeTabItem_DeleteEventItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Advanced Options.
        /// </summary>
        public static string HomeTabItem_EditEventItemText {
            get {
                return ResourceManager.GetString("HomeTabItem_EditEventItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string HomeTabItem_SaveChangesText {
            get {
                return ResourceManager.GetString("HomeTabItem_SaveChangesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XIVEVENT.
        /// </summary>
        public static string HomeTabItem_WelcomeText {
            get {
                return ResourceManager.GetString("HomeTabItem_WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainWindow_AboutButtonText {
            get {
                return ResourceManager.GetString("MainWindow_AboutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChatLog.
        /// </summary>
        public static string MainWindow_ChatLogButtonText {
            get {
                return ResourceManager.GetString("MainWindow_ChatLogButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string MainWindow_DebugButtonText {
            get {
                return ResourceManager.GetString("MainWindow_DebugButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MainWindow_HomeButtonText {
            get {
                return ResourceManager.GetString("MainWindow_HomeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainWindow_SettingsButtonText {
            get {
                return ResourceManager.GetString("MainWindow_SettingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent.
        /// </summary>
        public static string Palette_AccentText {
            get {
                return ResourceManager.GetString("Palette_AccentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Palette_DarkText {
            get {
                return ResourceManager.GetString("Palette_DarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Palette_LightText {
            get {
                return ResourceManager.GetString("Palette_LightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mid.
        /// </summary>
        public static string Palette_MidText {
            get {
                return ResourceManager.GetString("Palette_MidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary - Mid.
        /// </summary>
        public static string Palette_PrimaryMidText {
            get {
                return ResourceManager.GetString("Palette_PrimaryMidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent.
        /// </summary>
        public static string PaletteSelector_AccentText {
            get {
                return ResourceManager.GetString("PaletteSelector_AccentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string PaletteSelector_DarkText {
            get {
                return ResourceManager.GetString("PaletteSelector_DarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your current palette..
        /// </summary>
        public static string PaletteSelector_DescriptionText {
            get {
                return ResourceManager.GetString("PaletteSelector_DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string PaletteSelector_LightText {
            get {
                return ResourceManager.GetString("PaletteSelector_LightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary.
        /// </summary>
        public static string PaletteSelector_PrimaryText {
            get {
                return ResourceManager.GetString("PaletteSelector_PrimaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Directories.
        /// </summary>
        public static string SettingsTabItem_AudioDirectoriesHeaderText {
            get {
                return ResourceManager.GetString("SettingsTabItem_AudioDirectoriesHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Files.
        /// </summary>
        public static string SettingsTabItem_AudioFilesHeaderText {
            get {
                return ResourceManager.GetString("SettingsTabItem_AudioFilesHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Codes.
        /// </summary>
        public static string SettingsTabItem_ChatCodesTabHeaderText {
            get {
                return ResourceManager.GetString("SettingsTabItem_ChatCodesTabHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharlayan.
        /// </summary>
        public static string SettingsTabItem_SharlayanTabHeaderText {
            get {
                return ResourceManager.GetString("SettingsTabItem_SharlayanTabHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        public static string SettingsTabItem_SoundHeaderText {
            get {
                return ResourceManager.GetString("SettingsTabItem_SoundHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string SettingsTabItem_ThemeTabHeaderText {
            get {
                return ResourceManager.GetString("SettingsTabItem_ThemeTabHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Directory.
        /// </summary>
        public static string SoundSettings_AddDirectoryText {
            get {
                return ResourceManager.GetString("SoundSettings_AddDirectoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust global volume level. This will be applied to individual sound levels as well..
        /// </summary>
        public static string SoundSettings_AdjustmentText {
            get {
                return ResourceManager.GetString("SoundSettings_AdjustmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Devices.
        /// </summary>
        public static string SoundSettings_AudioDevicesText {
            get {
                return ResourceManager.GetString("SoundSettings_AudioDevicesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Directory.
        /// </summary>
        public static string SoundSettings_DeleteDirectoryText {
            get {
                return ResourceManager.GetString("SoundSettings_DeleteDirectoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each directory is top level scanned. The more files you have the greater the memory consumption of the application..
        /// </summary>
        public static string SoundSettings_DirectoriesText {
            get {
                return ResourceManager.GetString("SoundSettings_DirectoriesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        public static string SoundSettings_DirectoryText {
            get {
                return ResourceManager.GetString("SoundSettings_DirectoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Directory.
        /// </summary>
        public static string SoundSettings_EditDirectoryText {
            get {
                return ResourceManager.GetString("SoundSettings_EditDirectoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files are loaded from the level of available directories..
        /// </summary>
        public static string SoundSettings_FilesText {
            get {
                return ResourceManager.GetString("SoundSettings_FilesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Volume.
        /// </summary>
        public static string SoundSettings_MasterVolumeText {
            get {
                return ResourceManager.GetString("SoundSettings_MasterVolumeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Audio Devices.
        /// </summary>
        public static string SoundSettings_RefreshDevicesText {
            get {
                return ResourceManager.GetString("SoundSettings_RefreshDevicesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Audio Files.
        /// </summary>
        public static string SoundSettings_RereshFilesText {
            get {
                return ResourceManager.GetString("SoundSettings_RereshFilesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Audio.
        /// </summary>
        public static string SoundSettings_TestAudioText {
            get {
                return ResourceManager.GetString("SoundSettings_TestAudioText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Settings.
        /// </summary>
        public static string SoundSettings_VolumeSettingsText {
            get {
                return ResourceManager.GetString("SoundSettings_VolumeSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string UserSettings_ActionsHelperText {
            get {
                return ResourceManager.GetString("UserSettings_ActionsHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actor.
        /// </summary>
        public static string UserSettings_ActorHelperText {
            get {
                return ResourceManager.GetString("UserSettings_ActorHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust these timings to increase or decrease data latency. Faster timings may increase CPU usage..
        /// </summary>
        public static string UserSettings_AdjustmentText {
            get {
                return ResourceManager.GetString("UserSettings_AdjustmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChatLog.
        /// </summary>
        public static string UserSettings_ChatLogHelperText {
            get {
                return ResourceManager.GetString("UserSettings_ChatLogHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Player.
        /// </summary>
        public static string UserSettings_CurrentPlayerHelperText {
            get {
                return ResourceManager.GetString("UserSettings_CurrentPlayerHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Settings.
        /// </summary>
        public static string UserSettings_DataSettingsText {
            get {
                return ResourceManager.GetString("UserSettings_DataSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string UserSettings_InventoryHelperText {
            get {
                return ResourceManager.GetString("UserSettings_InventoryHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Resources.
        /// </summary>
        public static string UserSettings_JobResourcesHelperText {
            get {
                return ResourceManager.GetString("UserSettings_JobResourcesHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Timings.
        /// </summary>
        public static string UserSettings_MemoryTimingsText {
            get {
                return ResourceManager.GetString("UserSettings_MemoryTimingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Members.
        /// </summary>
        public static string UserSettings_PartyMembersHelperText {
            get {
                return ResourceManager.GetString("UserSettings_PartyMembersHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Settings.
        /// </summary>
        public static string UserSettings_ResetSettingsText {
            get {
                return ResourceManager.GetString("UserSettings_ResetSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string UserSettings_TargetHelperText {
            get {
                return ResourceManager.GetString("UserSettings_TargetHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use locally cached JSON for Sharlayan resources.
        /// </summary>
        public static string UserSettings_UseCachedDataText {
            get {
                return ResourceManager.GetString("UserSettings_UseCachedDataText", resourceCulture);
            }
        }
    }
}
